"""initial comic shop schema

Revision ID: 5b7d9022a40b
Revises: 
Create Date: 2026-07-11 13:19:25.627707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b7d9022a40b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('letterer',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('publisher',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('writer',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('comic',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('publication_date', sa.DateTime(), nullable=True),
    sa.Column('acquisition_date', sa.DateTime(), nullable=True),
    sa.Column('publisher_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('cover_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('variant', sa.String(length=100), nullable=True),
    sa.Column('asking_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('condition', sa.Enum('MINT', 'NEAR_MINT', 'VERY_FINE', 'FINE', 'VERY_GOOD', 'GOOD', 'FAIR', 'POOR', name='conditionenum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['publisher_id'], ['publisher.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('comic_artists',
    sa.Column('comic_id', sa.String(length=36), nullable=False),
    sa.Column('artist_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.uuid'], ),
    sa.ForeignKeyConstraint(['comic_id'], ['comic.uuid'], ),
    sa.PrimaryKeyConstraint('comic_id', 'artist_id')
    )
    op.create_table('comic_letterers',
    sa.Column('comic_id', sa.String(length=36), nullable=False),
    sa.Column('letterer_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['comic_id'], ['comic.uuid'], ),
    sa.ForeignKeyConstraint(['letterer_id'], ['letterer.uuid'], ),
    sa.PrimaryKeyConstraint('comic_id', 'letterer_id')
    )
    op.create_table('comic_price_history',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('comic_id', sa.String(length=36), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comic_id'], ['comic.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('comic_writers',
    sa.Column('comic_id', sa.String(length=36), nullable=False),
    sa.Column('writer_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['comic_id'], ['comic.uuid'], ),
    sa.ForeignKeyConstraint(['writer_id'], ['writer.uuid'], ),
    sa.PrimaryKeyConstraint('comic_id', 'writer_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comic_writers')
    op.drop_table('comic_price_history')
    op.drop_table('comic_letterers')
    op.drop_table('comic_artists')
    op.drop_table('comic')
    op.drop_table('writer')
    op.drop_table('publisher')
    op.drop_table('letterer')
    op.drop_table('artist')
    # ### end Alembic commands ###
